### ISSUE TITLE
DPU failed to create DataUnit

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/t-geonamesOrgToRdfFile#2]
When I run this DPU using ODN 1.0.1 installed from the odn-simple Debian package I get the following error:

```
Failed to prepare Context for DPURecord because of exception: cz.cuni.mff.xrg.odcs.backend.context.ContextException: Failed to create DataUnit.
at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:54)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.bind(DPUExecutor.java:147)
at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.execute(Executor.java:316)
at cz.cuni.mff.xrg.odcs.backend.execution.pipeline.Executor.run(Executor.java:429)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
at java.util.concurrent.FutureTask.run(FutureTask.java:262)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
at java.lang.Thread.run(Thread.java:745)
Caused by: eu.unifiedviews.dataunit.DataUnitException: No match in graph for ?o
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.getSingleObject(AbstractWritableMetadataDataUnit.java:513)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.access$000(AbstractWritableMetadataDataUnit.java:44)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit$4.execute(AbstractWritableMetadataDataUnit.java:329)
at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.innerExecute(FaultTolerantImpl.java:77)
at eu.unifiedviews.commons.dataunit.core.FaultTolerantImpl.execute(FaultTolerantImpl.java:41)
at eu.unifiedviews.commons.dataunit.AbstractWritableMetadataDataUnit.load(AbstractWritableMetadataDataUnit.java:309)
at cz.cuni.mff.xrg.odcs.backend.context.DataUnitManager.reload(DataUnitManager.java:207)
at cz.cuni.mff.xrg.odcs.backend.context.ContextRestorer.restore(ContextRestorer.java:28)
at cz.cuni.mff.xrg.odcs.backend.context.ContextFacade.create(ContextFacade.java:52)
```

What does `eu.unifiedviews.dataunit.DataUnitException: No match in graph for ?o` mean?

**Comment by ghost** [comment]
UV/Core bug
