### ISSUE TITLE
java.lang.VerifyError: Stack map does not match the one at exception handler 39

### ISSUE THREAD

**Issue by jindrichmynarz** [comsode-uv-plugins/t-geonamesOrgToRdfFile#4]
I recompiled the DPU from 6ca3d062f174f71ecc997a5754baac0159d974d4 and, when I used it, I got the following error:

```
Execution failed because: DPU.innerExecute throws throwable.eu.unifiedviews.dpu.DPUException: DPU.innerExecute throws throwable.
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:125)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.VerifyError: Stack map does not match the one at exception handler 39
Exception Details:
Location:
eu/unifiedviews/helpers/dataunit/metadata/MetadataUtilsInstance.getFirst(Lorg/openrdf/model/URI;)Lorg/openrdf/model/Value; @39: astore_2
Reason:
Type 'org/openrdf/query/MalformedQueryException' (current frame, stack[0]) is not assignable to 'org/openrdf/OpenRDFException' (stack map, stack[0])
Current Frame:
bci: @0
flags: { }
locals: { 'eu/unifiedviews/helpers/dataunit/metadata/MetadataUtilsInstance', 'org/openrdf/model/URI' }
stack: { 'org/openrdf/query/MalformedQueryException' }
Stackmap Frame:
bci: @39
flags: { }
locals: { 'eu/unifiedviews/helpers/dataunit/metadata/MetadataUtilsInstance', 'org/openrdf/model/URI' }
stack: { 'org/openrdf/OpenRDFException' }
Bytecode:
0000000: 2a2b b700 1e4d 2cb9 001f 0100 9900 192c
0000010: b900 2001 00c0 0021 1222 b900 2302 00b9
0000020: 0024 0100 b001 b04d bb00 2759 1228 2cb7
0000030: 0029 bf 
Exception Handler Table:
bci [0, 36] => handler: 39
bci [0, 36] => handler: 39
bci [0, 36] => handler: 39
bci [37, 38] => handler: 39
bci [37, 38] => handler: 39
bci [37, 38] => handler: 39
Stackmap Table:
append_frame(@37,Object[#141])
full_frame(@39,{Object[#120],Object[#142]},{Object[#143]})

at eu.unifiedviews.helpers.dataunit.metadata.MetadataUtils.create(MetadataUtils.java:59)
at eu.unifiedviews.helpers.dataunit.virtualpath.VirtualPathHelpers$VirtualPathHelperImpl.init(VirtualPathHelpers.java:132)
at eu.unifiedviews.helpers.dataunit.virtualpath.VirtualPathHelpers$VirtualPathHelperImpl.setVirtualPath(VirtualPathHelpers.java:157)
at eu.unifiedviews.helpers.dataunit.virtualpath.VirtualPathHelpers.setVirtualPath(VirtualPathHelpers.java:98)
at eu.comsode.unifiedviews.plugins.transformer.geonamesorgtontriples.GeonamesOrgToNTriples.innerExecute(GeonamesOrgToNTriples.java:57)
at eu.unifiedviews.helpers.dpu.exec.AbstractDpu.execute(AbstractDpu.java:117)
... 4 more
```

**Comment by ghost** [comment]
I have tried to contact you, please get online to speak about this.
